### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by paivett** [paivett/requests-curl#2]
The project needs unit testing!

**Comment by illume** [comment]
It would make sense to use the requests tests. How to do that exactly... needs research.

**Comment by abitrolly** [comment]
Done already? https://github.com/paivett/requests-curl/tree/master/tests

**Comment by paivett** [comment]
No, those tests account for roughly 57% of coverage. I will find some time to add more tests.

**Comment by abitrolly** [comment]
I've added https://github.com/paivett/requests-curl/pull/6 to just run the tests automatically with GitHub. It is possible to add coverage and PyPI publishing if I find time for this too. )

**Comment by paivett** [comment]
I have added unit tests with 99% of coverage. I will finally close this. I will see about github actions. Thanks.
